---
# Playbook that installs a database server, configures an admin user and restart the services

- name: install database server
  hosts: all

  tasks:
  - name: install mariadb database
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - mariadb-server
      - mariadb
      - MySQL-python

  - name: Enabling and starting services
    service:
      name: mariadb
      enabled: yes
      state: started

  - name: create mysql user
    mysql_user:
      name: redhat
      password: redhat
      priv: '*.*:ALL,GRANT'
      state: present
